<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>digital.pragmatech</groupId>
    <artifactId>spring-boot-testing-demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>spring-boot-testing-demo</name>
    <description>Experiment and Showcase Spring Boot Testing Features</description>

    <properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.3</version>
                <configuration>
<!--                    <redirectTestOutputToFile>true</redirectTestOutputToFile>-->
<!--                    <reportsDirectory>${project.build.directory}/test-reports</reportsDirectory>-->
                    <forkCount>2</forkCount>
                    <reuseForks>true</reuseForks>
                    <parallel>classes</parallel>
                    <argLine>-Xmx512m</argLine>
                    <threadCount>4</threadCount>
                    <systemPropertyVariables>
                        <test.timer.top.tests>15</test.timer.top.tests>
                        <test.timer.slow.threshold.ms>1000</test.timer.slow.threshold.ms>
                    </systemPropertyVariables>
                    <properties>

                        <configurationParameters>
                            junit.jupiter.execution.parallel.enabled=true
                            junit.jupiter.execution.parallel.mode.default=same_thread
                            junit.jupiter.execution.parallel.mode.classes.default=concurrent
                        </configurationParameters>
                    </properties>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
